apiVersion: v1
kind: pod
metadata: 
  name: urotaxi-pod
  labels:
    version: 1.0
spec:
  containers:
    - name: urotaxi
      image: techsriman/urotaxi:1.0
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP
      readinessProbe: 
        httpGet:
          path: roadster/actuator/health/readiness 
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3  
      livenessProbe:
        httpGet:
          path: roadster/actuator/health/liveness
          port: 8080  
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3  
      resources:
        requests: 
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1024Mi"
